export const APP_VERSION='1.7.0';
export const SEEN_KEY='sternklar-changelog-seen';
export const RELEASES=[
 {version:'1.7.0',title:'Ruhigere, einheitliche Buttons',changes:['Hauptaktionen, Nebenaktionen und Textbuttons folgen in der gesamten App derselben Form- und Farbwelt; die Akzentfläche ist weniger grell.','Auch auf der Update-Hilfeseite passt der Button zum neuen Design. In der Stundenansicht erscheint die Abrufzeit nur einmal.']},
 {version:'1.6.1',title:'Klareres Nachtwetter',changes:['Der Wetterabruf zeigt seinen Zeitstempel nur einmal; der kurze Abschluss erscheint als Rückmeldung nach dem Aktualisieren.','Die stündliche Wettervorhersage hat im Nachtfenster einen gut erkennbaren eigenen Button.']},
 {version:'1.6.0',title:'Für das iPhone verfeinert',changes:['Kompakteres Nachtfenster, bessere Fingerziele und eine handliche Navigation für schmale Bildschirme.','In Detailansichten führt ein Wisch vom linken Rand nach rechts zurück. Ein sichtbarer Zurück-Knopf bietet denselben Weg; Aufsuchkarte und Teilen kehren zum geöffneten Ziel zurück.']},
 {version:'1.5.2',title:'Wetter kompakter im Nachtfenster',changes:['Die Nachtprognose zeigt Kennzahlen, Hinweis und Abrufzeit mit deutlich weniger Abstand.','Aktualisieren und Stundenansicht sitzen nebeneinander; der Abrufstatus erscheint nur während oder nach einer Aktualisierung.']},
 {version:'1.5.1',title:'Ein Nachtfenster für Himmel und Wetter',changes:['Nachtverlauf und Wetterprognose stehen jetzt gemeinsam in einer Karte. Auf schmalen Bildschirmen folgen sie übersichtlich aufeinander.','Die Bortle-Eingabe erklärt Schritt für Schritt, wo du einen Kartenwert für deinen Standort findest und wie du ihn als Schätzung einordnest.']},
 {version:'1.5.0',title:'Nächte, Stunden und dein Himmel',changes:['Die nächsten sieben Nächte stehen direkt unter dem aktuellen Nachtwetter. Ein Tipp auf eine Nacht öffnet deren übersichtliche Stundenprognose.','Für jeden Beobachtungsplatz lässt sich eine Bortle-Klasse von 1 bis 9 eintragen und dauerhaft speichern. Ein Kartenlink hilft bei der Einordnung; der Wert wird nicht als automatische Messung ausgegeben.','Auf dem iPhone lassen sich die sieben Nächte bequem horizontal durchwischen.']},
 {version:'1.4.3',title:'Die nächsten sieben Nächte beginnen heute',changes:['Die Wochenübersicht startet mit dem heutigen Kalendertag am eingestellten Standort, auch am Vormittag.','Ab 08:00 Uhr zeigt „Heute Nacht“ die kommende Nacht. Eine geöffnete App stellt die Vorschau beim Tageswechsel automatisch um, ohne manuell gewählte Nächte zu überschreiben.']},
 {version:'1.4.2',title:'Wetterfenster direkt in der Höhenkurve',changes:['Empfohlene Ziele zeigen astronomische Sichtbarkeit und wettergünstige Abschnitte in zwei Farben auf derselben Uhrzeitachse.','Die Zielansicht zeigt dieselbe Darstellung mit Uhrzeiten und einer Legende. Fehlende oder veraltete Prognosen werden nicht als günstiges Wetter gezeichnet.']},
 {version:'1.4.1',title:'Wetterfenster pro Ziel',changes:['Empfohlene Ziele zeigen neben der astronomischen Sichtbarkeit eine geschätzte Fotozeit aus der stündlichen Wetterprognose.','Wetterfenster berücksichtigen nur die Zeiten, in denen das Ziel über deinem Horizont steht. Bei fehlender oder veralteter Prognose wird kein Wetterfenster behauptet.','Nach einer Wetteraktualisierung passen sich die Angaben direkt an.']},
 {version:'1.4.0',title:'Ziele passend zum aktiven Teleskop',changes:['Die Empfehlungen gewichten die Objektgröße im Bildfeld des aktiven Teleskops stärker. Sehr kleine Motive, knapp angeschnittene Ziele und nötige Mosaike werden niedriger bewertet.','Die Empfehlung zeigt das verwendete Teleskop und sein Bildfeld. Beim Teleskopwechsel werden die Vorschläge sofort neu berechnet.','Die verbesserte Bewertung gilt auch im Katalog und für die Planvorschläge pro Teleskop.']},
 {version:'1.3.1',title:'Wetter sichtbar aktualisieren',changes:['Direkter Aktualisieren-Button in der Nachtvorhersage und im Stundenwetter.','Sichtbarer Abrufstatus, Zeitstempel mit Sekunden und Rückmeldung bei unveränderten Vorhersagen.','Manuelle Aktualisierung umgeht den Wettercache. Fehler werden klar angezeigt; gespeicherte Prognosen bleiben als veraltet erkennbar.']},
 {version:'1.3.0',title:'Neuigkeiten immer im Blick',changes:['Die Versionshistorie ist jetzt in den Einstellungen unter „Was ist neu? / Changelog“ erreichbar.','Nach einem Update erscheinen die Neuigkeiten einmalig. Nach dem Schließen bleiben sie in der Versionshistorie nachlesbar.']},
 {version:'1.2.4',title:'Alle Teleskope im Bildfeldvergleich',changes:['„Passt es in dein Bild?“ zeigt alle ausgewählten Teleskope und eigenen Setups.','Eine separate Legende mit Bildfeldmaßen, Farben und Linienmustern erleichtert den Vergleich.']},
 {version:'1.2.3',title:'Update-Meldungen schließen',changes:['Reine Statusmeldungen lassen sich vollständig schließen und verschwinden beim Seitenwechsel.']},
 {version:'1.2.2',title:'Update-Veröffentlichung korrigiert',changes:['Ein Ladefehler der Version 1.2.1 wurde behoben.']},
 {version:'1.2.1',title:'Updates auf Knopfdruck',changes:['Ein fester Button in den Einstellungen prüft auf Updates und meldet den aktuellen Stand.','Verfügbare Updates lassen sich direkt aktivieren, ohne die App schließen zu müssen.']},
 {version:'1.2.0',title:'Ziele für Mosaike finden',changes:['Der Filter „Mosaik sinnvoll“ berücksichtigt das Bildfeld des aktiven Teleskops und die Objektgröße.']},
 {version:'1.1.1',title:'Ältere Installationen aktualisieren',changes:['Ein separater Update-Assistent hilft bei festhängenden älteren Versionen.','Neue App-Dateien werden beim Update frisch geladen.']},
 {version:'1.1.0',title:'Sichere Updates und Origin Mark II',changes:['Update-Hinweise mit bewusster Aktivierung und lokaler Sicherung der gespeicherten Daten.','Sicherung wiederherstellen und Originaldaten exportieren.','Celestron Origin Mark II als Teleskopprofil ergänzt.']},
 {version:'1.0.0',title:'Sternklar startet',changes:['Astroplanung mit Deep-Sky-Katalog, Nachtfenstern, Mond, Wetter und persönlichem Horizont.','Teleskopauswahl, Bildfeldvergleich, Merklisten, Aufnahmen und Aufnahmepläne.','Installierbare Home-Screen-App mit Offline-Katalog und Datensicherung.']}
];
export function newer(a,b){const x=a.split('.').map(Number),y=b.split('.').map(Number);for(let i=0;i<3;i++){if(x[i]!==y[i])return x[i]>y[i];}return false;}
export function unseenReleases(storage){
 try{
  const seen=storage.getItem(SEEN_KEY);
  if(!seen){if(storage.getItem('sternklar-v1')!==null)return [RELEASES[0]];acknowledgeRelease(storage);return [];}
  if(!/^\d+\.\d+\.\d+$/.test(seen))return [RELEASES[0]];
  return RELEASES.filter(r=>newer(r.version,seen));
 }catch{return [];}
}
export function acknowledgeRelease(storage){try{const seen=storage.getItem(SEEN_KEY);if(!seen||!/^\d+\.\d+\.\d+$/.test(seen)||newer(APP_VERSION,seen))storage.setItem(SEEN_KEY,APP_VERSION);}catch{/* Storage restrictions must not block the app. */}}
