import {time,DIRS,fov,starEq,bodyAt} from './astro.js';
const A=globalThis.Astronomy,R=Math.PI/180;
export function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function curve(t,ctx,detail=false){const w=600,h=detail?210:100,left=detail?35:0,bottom=detail?30:0,iw=w-left-10,ih=h-bottom-10;const x=p=>left+(p.d-ctx.start)/(ctx.end-ctx.start)*iw,y=v=>5+(90-Math.max(0,v))/90*ih;const path=t.points.map((p,i)=>`${i?'L':'M'}${x(p).toFixed(1)},${y(p.alt).toFixed(1)}`).join(' ');const blocked=t.points.map((p,i)=>`${i?'L':'M'}${x(p).toFixed(1)},${y(p.floor).toFixed(1)}`).join(' ');let guides='';if(detail){for(const n of[0,30,60,90])guides+=`<line x1="${left}" y1="${y(n)}" x2="${w}" y2="${y(n)}" stroke="var(--line)"/><text x="0" y="${y(n)+5}" fill="var(--muted)" font-size="12">${n}°</text>`;for(const hour of[0,6,12,18,24]){const d=new Date(+ctx.start+hour*36e5);if(d>ctx.end)continue;guides+=`<text x="${x({d})}" y="${h-2}" text-anchor="${hour===24?'end':'middle'}" fill="var(--muted)" font-size="12">${time(d,ctx.loc.tz)}</text>`;}}
 const darkRects=ctx.dark.map(s=>`<rect x="${x(s)}" y="5" width="${iw*ctx.step/(ctx.end-ctx.start)+.2}" height="${ih}" fill="var(--accent)" opacity=".05"/>`).join('');
 const visible=t.points.filter(p=>p.visible).map(p=>`<circle cx="${x(p)}" cy="${y(p.alt)}" r="${detail?2:1.8}" fill="var(--accent)"/>`).join('');return `<svg class="${detail?'detail-chart':'sparkline'}" viewBox="0 0 ${w} ${h}" role="img" aria-label="Höhenverlauf von ${esc(t.name)}. Maximum ${Math.round(t.peak.alt)} Grad um ${time(t.peak.d,ctx.loc.tz)}. ${t.hours.toFixed(1)} Stunden nutzbar.">${darkRects}${guides}<path d="${blocked}" fill="none" stroke="var(--gold)" stroke-dasharray="4 5" opacity=".5"/><path d="${path}" fill="none" stroke="var(--muted)" stroke-width="1.6"/>${visible}</svg>`;}
export function fovChart(t,scopes){const frames=scopes.map(s=>({s,...fov(s)}));const extent=Math.max(t.major||20,...frames.flatMap(f=>[f.w,f.h]))*1.3;const scale=300/extent,cx=200,cy=140;const target=`<ellipse cx="${cx}" cy="${cy}" rx="${(t.major||10)*scale/2}" ry="${(t.minor||t.major||10)*scale/2}" fill="var(--muted)" opacity=".24"/><text x="${cx}" y="${cy+5}" text-anchor="middle" fill="var(--text)" font-size="13">${esc(t.id)}</text>`;return `<svg class="fov-canvas" viewBox="0 0 400 280" role="img" aria-label="Maßstäblicher Sichtfeldvergleich; Objekt als Ellipse, drehbare Kamera angenommen">${target}${frames.map((f,i)=>`<rect x="${cx-f.w*scale/2}" y="${cy-f.h*scale/2}" width="${f.w*scale}" height="${f.h*scale}" fill="none" stroke="${i?'var(--gold)':'var(--accent)'}" stroke-width="2" ${i?'stroke-dasharray="5 4"':''}/><text x="12" y="${22+i*20}" fill="${i?'var(--gold)':'var(--accent)'}" font-size="13">${esc(f.s.name)} · ${(f.w/60).toFixed(2)}° × ${(f.h/60).toFixed(2)}°</text>`).join('')}</svg>`;}
export function skyChart(stars,targets,ctx,d,labels=true,constellations=null,lines=true){const cx=260,cy=260,radius=215;const project=h=>({x:cx+radius*(90-h.altitude)/90*Math.sin(h.azimuth*R),y:cy-radius*(90-h.altitude)/90*Math.cos(h.azimuth*R)});const rot=A.Rotation_EQJ_EQD(d);let svg=`<circle cx="${cx}" cy="${cy}" r="${radius}" fill="var(--bg)" stroke="var(--line)"/>`;for(const alt of[30,60])svg+=`<circle cx="${cx}" cy="${cy}" r="${radius*(90-alt)/90}" fill="none" stroke="var(--line)" stroke-dasharray="3 6"/>`;DIRS.forEach((dir,i)=>{const az=i*45*R;svg+=`<text x="${cx+238*Math.sin(az)}" y="${cy-238*Math.cos(az)+5}" fill="var(--muted)" text-anchor="middle" font-size="15">${dir}</text>`;});
 const hor=Array.from({length:361},(_,az)=>{const h=ctx.loc.horizon||Array(8).fill(0),i=Math.floor(az/45)%8,f=(az%45)/45;return project({azimuth:az,altitude:h[i]*(1-f)+h[(i+1)%8]*f});});svg+=`<path d="${hor.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ')}Z" fill="none" stroke="var(--gold)" opacity=".5"/>`;
 if(lines&&constellations)for(const feature of constellations.features)for(const line of feature.geometry.coordinates){let last=null;for(const [ra,dec]of line){const eq=starEq(((ra+360)%360)/15,dec,d,rot),h=A.Horizon(d,ctx.obs,eq.ra,eq.dec,'normal'),p=project(h);if(last&&h.altitude>0&&last.alt>0)svg+=`<line x1="${last.p.x}" y1="${last.p.y}" x2="${p.x}" y2="${p.y}" stroke="var(--muted)" opacity=".27"/>`;last={p,alt:h.altitude};}}
 for(const star of stars){const eq=starEq(star.ra,star.dec,d,rot),h=A.Horizon(d,ctx.obs,eq.ra,eq.dec,'normal');if(h.altitude<=0)continue;const p=project(h);svg+=`<circle cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(1)}" r="${Math.max(.45,2-star.mag*.27)}" fill="var(--text)" opacity=".7"/>`;}
 for(const t of targets.slice(0,16)){const eq=starEq(t.ra,t.dec,d,rot),h=A.Horizon(d,ctx.obs,eq.ra,eq.dec,'normal');if(h.altitude<0)continue;const p=project(h);svg+=`<circle cx="${p.x}" cy="${p.y}" r="5" fill="var(--bg)" stroke="var(--accent)"/><title>${esc(t.name)}</title>${labels?`<text x="${p.x+8}" y="${p.y+4}" fill="var(--accent)" font-size="12">${esc(t.id)}</text>`:''}`;}
 const moon=bodyAt('Moon',d,ctx.obs);if(moon.altitude>0){const p=project(moon);svg+=`<circle cx="${p.x}" cy="${p.y}" r="7" fill="var(--gold)"/><text x="${p.x+10}" y="${p.y+4}" fill="var(--gold)" font-size="12">Mond</text>`;}return `<svg class="sky-chart" viewBox="0 0 520 520" role="img" aria-label="Himmelskarte: Norden oben, Osten rechts. Zenit in der Mitte, Horizont außen.">${svg}<text x="260" y="512" text-anchor="middle" fill="var(--muted)" font-size="12">N oben · O rechts · Zenit in der Mitte · ${time(d,ctx.loc.tz)}</text></svg>`;}

export function finderChart(t,stars,constellations,field,scope,labels=true,lines=true){const k=230/Math.tan(field/2*R),a=t.ra*15*R,b=t.dec*R;const proj=(ra,dec)=>{const da=ra*15*R-a,dr=dec*R,cosc=Math.sin(b)*Math.sin(dr)+Math.cos(b)*Math.cos(dr)*Math.cos(da);if(cosc<=0)return null;return {x:260-k*Math.cos(dr)*Math.sin(da)/cosc,y:260-k*(Math.cos(b)*Math.sin(dr)-Math.sin(b)*Math.cos(dr)*Math.cos(da))/cosc};};let svg='<defs><clipPath id="finder-clip"><rect x="20" y="20" width="480" height="480" rx="10"/></clipPath></defs><rect x="20" y="20" width="480" height="480" rx="10" fill="var(--bg)" stroke="var(--line)"/><g clip-path="url(#finder-clip)">';if(lines)for(const feature of constellations.features)for(const line of feature.geometry.coordinates){let last;for(const[ra,dec]of line){const p=proj(((ra+360)%360)/15,dec);if(p&&last&&Math.abs(p.x-last.x)<1000&&Math.abs(p.y-last.y)<1000)svg+=`<line x1="${last.x}" y1="${last.y}" x2="${p.x}" y2="${p.y}" stroke="var(--muted)" opacity=".3"/>`;last=p;}}for(const s of stars){const p=proj(s.ra,s.dec);if(!p||p.x<20||p.x>500||p.y<20||p.y>500)continue;svg+=`<circle cx="${p.x}" cy="${p.y}" r="${Math.max(1,4-s.mag*.5)}" fill="var(--text)"/>`;}const f=fov(scope),scale=460/field;svg+=`<rect x="${260-f.w/60*scale/2}" y="${260-f.h/60*scale/2}" width="${f.w/60*scale}" height="${f.h/60*scale}" fill="none" stroke="var(--gold)" stroke-dasharray="6 5"/><ellipse cx="260" cy="260" rx="${(t.major||1)/60*scale/2}" ry="${(t.minor||t.major||1)/60*scale/2}" fill="var(--accent)" opacity=".3"/><path d="M248 260h24M260 248v24" stroke="var(--accent)"/>${labels?`<text x="275" y="245" fill="var(--accent)" font-size="15">${esc(t.id)}</text>`:''}</g><text x="260" y="15" text-anchor="middle" fill="var(--muted)" font-size="13">N · ${field}° Ausschnitt · Osten links</text><text x="260" y="518" text-anchor="middle" fill="var(--gold)" font-size="13">${esc(scope.name)} · Sensorrahmen</text>`;return `<svg class="sky-chart" viewBox="0 0 520 530" role="img" aria-label="Aufsuchkarte von ${esc(t.name)} mit ${field} Grad Sichtfeld und Sensorrahmen">${svg}</svg>`;}
